version: '3.1'

services: 
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    volumes:
       - postgresdb-volume:/var/lib/postgresql/data 

    ports:
       - 5435:5432

volumes: 
  postgresdb-volume: {}
